data:
  raw_path: 'C:\Users\mikol\Repositories\Nestle\data\raw\historical_sales_volume.csv'

model:
  path: 'C:\Users\mikol\Repositories\Nestle\models\arima_model.pkl'

logs:
  path: 'C:\Users\mikol\Repositories\Nestle\config\model\logs.txt'

param_grid:
  order:
    - [1, 1, 1]
    - [1, 1, 2]
    - [2, 1, 1]
    - [2, 1, 2]
    - [3, 1, 1]
    - [3, 1, 2]
    - [3, 1, 3]
    - [4, 1, 1]
    - [4, 1, 2]
  seasonal_order:
    - [0, 0, 0, 0]
    - [1, 0, 0, 4]
    - [1, 1, 0, 4]
    - [0, 1, 1, 4]
    - [1, 1, 1, 4]
  trend:
    - 'n'
    - 'c'
    - 't'
    - 'ct'
  enforce_stationarity:
    - True
    - False
  enforce_invertibility:
    - True
    - False

evaluation:
  metrics: 'neg_mean_squared_error'
